language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database postit_db_test;' -U postgres
- npm run build-server
- sequelize db:migrate
- sequelize db:seed:all
script: npm test
after_success: npm run coverage
cache:
  directories:
    - "node_modules"