language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- npm install codeclimate-test-reporter istanbul -g
- psql -c 'create database postit_db_test;' -U postgres
- npm run build-server
- sequelize db:migrate
- sequelize db:seed:all
script: npm test
after_script: 
- sudo service postgresql stop
after_success: 
- npm run coverage
- codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
    - "node_modules"
